'22' = []
'TEST' = []
'a0' = []
'a1' = []
'name_1' = ["idValue1", ""]
'name_2' = ["idValue2", ""]
'name_3' = [""]
'name_5' = []
'ЕУЫЕ' = []
'ввывы' = []

'name_11' = ["idValue1", ""]
'name_12' = ["idValue2", ""]
'name_13' = [""]
'name_15' = []

'name_21' = ["idValue_1", ""]
'name_22' = ["idValue2", ""]
'name_23' = [""]
'name_25' = []
