name: 'publish'

on:
  push:
    branches:
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup PNPM and Node.js Action
        uses: digi-fry/setup-pnpm-node-action@v1
        with:
          node-version: 20
          pnpm-version: 9
          

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
        
      - name: install frontend dependencies
        run: pnpm i # change this to npm, pnpm or bun depending on which one you use.
      
      - name: custom-tauri-action
        uses: naveennaidu/tauri-action@v1

                
